CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS features;
CREATE SCHEMA IF NOT EXISTS metadata;

CREATE SCHEMA IF NOT EXISTS mlopt;
CREATE SCHEMA IF NOT EXISTS mltrain;
